
#ifndef __CUSTOM_MEMORYDEVICE__
#define __CUSTOM_MEMORYDEVICE__



#define BOARD_ID                MT6575_EVB

#define CS_PART_NUMBER[0]       H9TP32A4GDMCPR_KDM
//#define CS_PART_NUMBER[1]       H9TP32A8JDMCPR_KGM

#endif /* __CUSTOM_MEMORYDEVICE__ */
